// automatically generated by the FlatBuffers compiler, do not modify

package gg.generationsmod.rarecandy.model.animation.gfbanm;

public class BoneInitT {
  private long isInit;
  private TransformT transform;

  public long getIsInit() { return isInit; }

  public void setIsInit(long isInit) { this.isInit = isInit; }

  public TransformT getTransform() { return transform; }

  public void setTransform(TransformT transform) { this.transform = transform; }


  public BoneInitT() {
    this.isInit = 0L;
    this.transform = new TransformT();
  }
}

