// automatically generated by the FlatBuffers compiler, do not modify

package gg.generationsmod.rarecandy.model.animation.gfbanm;

@SuppressWarnings("unused")
public final class ByteTrack {
  private ByteTrack() { }
  public static final byte NONE = 0;
  public static final byte FixedByteTrack = 1;
  public static final byte DynamicByteTrack = 2;
  public static final byte Framed16ByteTrack = 3;
  public static final byte Framed8ByteTrack = 4;

  public static final String[] names = { "NONE", "FixedByteTrack", "DynamicByteTrack", "Framed16ByteTrack", "Framed8ByteTrack", };

  public static String name(int e) { return names[e]; }
}

