// automatically generated by the FlatBuffers compiler, do not modify

package gg.generationsmod.rarecandy.model.animation.gfbanm;

public class ByteDataTrackT {
  private int value;

  public int getValue() { return value; }

  public void setValue(int value) { this.value = value; }


  public ByteDataTrackT() {
    this.value = 0;
  }
}

