// automatically generated by the FlatBuffers compiler, do not modify

package gg.generationsmod.rarecandy.model.animation.gfbanm;

public class ColorEntryT {
  private String name;
  private VectorTrackUnion col;

  public String getName() { return name; }

  public void setName(String name) { this.name = name; }

  public VectorTrackUnion getCol() { return col; }

  public void setCol(VectorTrackUnion col) { this.col = col; }


  public ColorEntryT() {
    this.name = null;
    this.col = null;
  }
}

