// automatically generated by the FlatBuffers compiler, do not modify

package gg.generationsmod.rarecandy.model.animation.gfbanm;

public class CommandAnimationT {
  private CommandTrackT[] tracks;

  public CommandTrackT[] getTracks() { return tracks; }

  public void setTracks(CommandTrackT[] tracks) { this.tracks = tracks; }


  public CommandAnimationT() {
    this.tracks = null;
  }
}

