// automatically generated by the FlatBuffers compiler, do not modify

package gg.generationsmod.rarecandy.model.animation.gfbanm;

public class CommandTrackT {
  private String name;
  private long frameStart;
  private long frameLen;
  private CommandEntryT[] vec;

  public String getName() { return name; }

  public void setName(String name) { this.name = name; }

  public long getFrameStart() { return frameStart; }

  public void setFrameStart(long frameStart) { this.frameStart = frameStart; }

  public long getFrameLen() { return frameLen; }

  public void setFrameLen(long frameLen) { this.frameLen = frameLen; }

  public CommandEntryT[] getVec() { return vec; }

  public void setVec(CommandEntryT[] vec) { this.vec = vec; }


  public CommandTrackT() {
    this.name = null;
    this.frameStart = 0L;
    this.frameLen = 0L;
    this.vec = null;
  }
}

