// automatically generated by the FlatBuffers compiler, do not modify

package gg.generationsmod.rarecandy.model.animation.gfbanm;

public class DynamicByteTrackT {
  private int[] byte_;

  public int[] getByte() { return byte_; }

  public void setByte(int[] byte_) { this.byte_ = byte_; }


  public DynamicByteTrackT() {
    this.byte_ = null;
  }
}

