// automatically generated by the FlatBuffers compiler, do not modify

package gg.generationsmod.rarecandy.model.animation.gfbanm;

import gg.generationsmod.rarecandy.model.animation.TranmUtil;
import gg.generationsmod.rarecandy.model.animation.TransformStorage;
import org.joml.Quaternionf;

public class DynamicRotationTrackT implements TrackProcesser<Quaternionf> {
  private sVec3T[] co;

  public sVec3T[] getCo() { return co; }

  public void setCo(sVec3T[] co) { this.co = co; }


  public DynamicRotationTrackT() {
    this.co = null;
  }

  @Override
  public void process(TransformStorage<Quaternionf> rotationKeys) {
    for (int i = 0; i < co.length; i++) {
      var vec = co[i];
      rotationKeys.add(i, TranmUtil.packedToQuat((short) vec.getX(), (short) vec.getY(), (short) vec.getZ()));
    }
  }
}

