// automatically generated by the FlatBuffers compiler, do not modify

package gg.generationsmod.rarecandy.model.animation.gfbanm;

public class FixedBooleanTrackT {
  private boolean bool;

  public boolean getBool() { return bool; }

  public void setBool(boolean bool) { this.bool = bool; }


  public FixedBooleanTrackT() {
    this.bool = false;
  }
}

