// automatically generated by the FlatBuffers compiler, do not modify

package gg.generationsmod.rarecandy.model.animation.gfbanm;

import gg.generationsmod.rarecandy.model.animation.TransformStorage;

public class FixedFloatTrackT implements TrackProcesser<Float> {
  private float float_;

  public float getFloat() { return float_; }

  public void setFloat(float float_) { this.float_ = float_; }


  public FixedFloatTrackT() {
    this.float_ = 0.0f;
  }

  @Override
  public void process(TransformStorage<Float> keys) {
    keys.add(0, float_);

  }
}

