// automatically generated by the FlatBuffers compiler, do not modify

package gg.generationsmod.rarecandy.model.animation.gfbanm;

import gg.generationsmod.rarecandy.model.animation.TranmUtil;
import gg.generationsmod.rarecandy.model.animation.TransformStorage;
import org.joml.Quaternionf;

public class FixedRotationTrackT implements TrackProcesser<Quaternionf> {
  private sVec3T co;

  public sVec3T getCo() { return co; }

  public void setCo(sVec3T co) { this.co = co; }


  public FixedRotationTrackT() {
    this.co = new sVec3T();
  }

  @Override
  public void process(TransformStorage<Quaternionf> rotationKeys) {
    rotationKeys.add(0, TranmUtil.packedToQuat((short) co.getX(), (short) co.getY(), (short) co.getZ()));
  }
}

