// automatically generated by the FlatBuffers compiler, do not modify

package gg.generationsmod.rarecandy.model.animation.gfbanm;

@SuppressWarnings("unused")
public final class FloatTrack {
  private FloatTrack() { }
  public static final byte NONE = 0;
  public static final byte FixedFloatTrack = 1;
  public static final byte DynamicFloatTrack = 2;
  public static final byte Framed16FloatTrack = 3;
  public static final byte Framed8FloatTrack = 4;

  public static final String[] names = { "NONE", "FixedFloatTrack", "DynamicFloatTrack", "Framed16FloatTrack", "Framed8FloatTrack", };

  public static String name(int e) { return names[e]; }
}

