// automatically generated by the FlatBuffers compiler, do not modify

package gg.generationsmod.rarecandy.model.animation.gfbanm;

public class FloatDataTrackT {
  private float value;

  public float getValue() { return value; }

  public void setValue(float value) { this.value = value; }


  public FloatDataTrackT() {
    this.value = 0.0f;
  }
}

