// automatically generated by the FlatBuffers compiler, do not modify

package gg.generationsmod.rarecandy.model.animation.gfbanm;

public class Framed16BooleanTrackT {
  private int[] frames;
  private boolean[] bool;

  public int[] getFrames() { return frames; }

  public void setFrames(int[] frames) { this.frames = frames; }

  public boolean[] getBool() { return bool; }

  public void setBool(boolean[] bool) { this.bool = bool; }


  public Framed16BooleanTrackT() {
    this.frames = null;
    this.bool = null;
  }
}

