// automatically generated by the FlatBuffers compiler, do not modify

package gg.generationsmod.rarecandy.model.animation.gfbanm;

import gg.generationsmod.rarecandy.model.animation.TranmUtil;
import gg.generationsmod.rarecandy.model.animation.TransformStorage;
import org.joml.Quaternionf;

public class Framed16RotationTrackT implements TrackProcesser<Quaternionf> {
  private int[] frames;
  private sVec3T[] co;

  public int[] getFrames() { return frames; }

  public void setFrames(int[] frames) { this.frames = frames; }

  public sVec3T[] getCo() { return co; }

  public void setCo(sVec3T[] co) { this.co = co; }


  public Framed16RotationTrackT() {
    this.frames = null;
    this.co = null;
  }

  @Override
  public void process(TransformStorage<Quaternionf> rotationKeys) {
    var frames = getFrames();
    for (int i = 0; i < getFrames().length; i++) {
      var vec = getCo()[i];
      rotationKeys.add(frames[i], TranmUtil.packedToQuat((short) vec.getX(), (short) vec.getY(), (short) vec.getZ()));
    }
  }
}

