// automatically generated by the FlatBuffers compiler, do not modify

package gg.generationsmod.rarecandy.model.animation.gfbanm;

public class Framed16ByteTrackT {
  private int[] frames;
  private int[] byte_;

  public int[] getFrames() { return frames; }

  public void setFrames(int[] frames) { this.frames = frames; }

  public int[] getByte() { return byte_; }

  public void setByte(int[] byte_) { this.byte_ = byte_; }


  public Framed16ByteTrackT() {
    this.frames = null;
    this.byte_ = null;
  }
}

