// automatically generated by the FlatBuffers compiler, do not modify

package gg.generationsmod.rarecandy.model.animation.gfbanm;

import com.google.flatbuffers.*;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Framed8FloatTrack extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static Framed8FloatTrack getRootAsFramed8FloatTrack(ByteBuffer _bb) { return getRootAsFramed8FloatTrack(_bb, new Framed8FloatTrack()); }
  public static Framed8FloatTrack getRootAsFramed8FloatTrack(ByteBuffer _bb, Framed8FloatTrack obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Framed8FloatTrack __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int frames(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int framesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector framesVector() { return framesVector(new ByteVector()); }
  public ByteVector framesVector(ByteVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer framesAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer framesInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public float float_(int j) { int o = __offset(6); return o != 0 ? bb.getFloat(__vector(o) + j * 4) : 0; }
  public int float_Length() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public FloatVector floatVector() { return floatVector(new FloatVector()); }
  public FloatVector floatVector(FloatVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer float_AsByteBuffer() { return __vector_as_bytebuffer(6, 4); }
  public ByteBuffer float_InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 4); }

  public static int createFramed8FloatTrack(FlatBufferBuilder builder,
      int framesOffset,
      int float_Offset) {
    builder.startTable(2);
    Framed8FloatTrack.addFloat(builder, float_Offset);
    Framed8FloatTrack.addFrames(builder, framesOffset);
    return Framed8FloatTrack.endFramed8FloatTrack(builder);
  }

  public static void startFramed8FloatTrack(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addFrames(FlatBufferBuilder builder, int framesOffset) { builder.addOffset(0, framesOffset, 0); }
  public static int createFramesVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createFramesVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startFramesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addFloat(FlatBufferBuilder builder, int float_Offset) { builder.addOffset(1, float_Offset, 0); }
  public static int createFloatVector(FlatBufferBuilder builder, float[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addFloat(data[i]); return builder.endVector(); }
  public static void startFloatVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endFramed8FloatTrack(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Framed8FloatTrack get(int j) { return get(new Framed8FloatTrack(), j); }
    public Framed8FloatTrack get(Framed8FloatTrack obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public Framed8FloatTrackT unpack() {
    Framed8FloatTrackT _o = new Framed8FloatTrackT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(Framed8FloatTrackT _o) {
    int[] _oFrames = new int[framesLength()];
    for (int _j = 0; _j < framesLength(); ++_j) {_oFrames[_j] = frames(_j);}
    _o.setFrames(_oFrames);
    float[] _oFloat = new float[float_Length()];
    for (int _j = 0; _j < float_Length(); ++_j) {_oFloat[_j] = float_(_j);}
    _o.setFloat(_oFloat);
  }
  public static int pack(FlatBufferBuilder builder, Framed8FloatTrackT _o) {
    if (_o == null) return 0;
    int _frames = 0;
    if (_o.getFrames() != null) {
      byte[] __frames = new byte[_o.getFrames().length];
      int _j = 0;
      for (int _e : _o.getFrames()) { __frames[_j] = (byte) _e; _j++;}
      _frames = createFramesVector(builder, __frames);
    }
    int _float_ = 0;
    if (_o.getFloat() != null) {
      _float_ = createFloatVector(builder, _o.getFloat());
    }
    return createFramed8FloatTrack(
      builder,
      _frames,
      _float_);
  }
}

