// automatically generated by the FlatBuffers compiler, do not modify

package gg.generationsmod.rarecandy.model.animation.gfbanm;

public class InfoT {
  private long doesLoop;
  private long keyFrames;
  private long frameRate;

  public long getDoesLoop() { return doesLoop; }

  public void setDoesLoop(long doesLoop) { this.doesLoop = doesLoop; }

  public long getKeyFrames() { return keyFrames; }

  public void setKeyFrames(long keyFrames) { this.keyFrames = keyFrames; }

  public long getFrameRate() { return frameRate; }

  public void setFrameRate(long frameRate) { this.frameRate = frameRate; }


  public InfoT() {
    this.doesLoop = 0L;
    this.keyFrames = 0L;
    this.frameRate = 0L;
  }
}

