// automatically generated by the FlatBuffers compiler, do not modify

package gg.generationsmod.rarecandy.model.animation.gfbanm;

public class IntDataTrackT {
  private long value;

  public long getValue() { return value; }

  public void setValue(long value) { this.value = value; }


  public IntDataTrackT() {
    this.value = 0L;
  }
}

