// automatically generated by the FlatBuffers compiler, do not modify

package gg.generationsmod.rarecandy.model.animation.gfbanm;

public class MaterialAnimationT {
  private MaterialTrackT[] tracks;

  public MaterialTrackT[] getTracks() { return tracks; }

  public void setTracks(MaterialTrackT[] tracks) { this.tracks = tracks; }


  public MaterialAnimationT() {
    this.tracks = null;
  }
}

