// automatically generated by the FlatBuffers compiler, do not modify

package gg.generationsmod.rarecandy.model.animation.gfbanm;

public class SkinAnimationT {
  private SkinTrackT[] tracks;

  public SkinTrackT[] getTracks() { return tracks; }

  public void setTracks(SkinTrackT[] tracks) { this.tracks = tracks; }


  public SkinAnimationT() {
    this.tracks = null;
  }
}

