// automatically generated by the FlatBuffers compiler, do not modify

package gg.generationsmod.rarecandy.model.animation.gfbanm;

public class StringDataTrackT {
  private String value;

  public String getValue() { return value; }

  public void setValue(String value) { this.value = value; }


  public StringDataTrackT() {
    this.value = null;
  }
}

