// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.pokeutils.tranm;

@SuppressWarnings("unused")
public final class QuatTrack {
    public static final byte NONE = 0;
    public static final byte FixedQuatTrack = 1;
    public static final byte DynamicQuatTrack = 2;
    public static final byte Framed16QuatTrack = 3;
    public static final byte Framed8QuatTrack = 4;
    public static final String[] names = {"NONE", "FixedQuatTrack", "DynamicQuatTrack", "Framed16QuatTrack", "Framed8QuatTrack",};

    private QuatTrack() {
    }

    public static String name(int e) {
        return names[e];
    }
}

