// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.pokeutils.tranm;

@SuppressWarnings("unused")
public final class VectorTrack {
  private VectorTrack() { }
  public static final byte NONE = 0;
  public static final byte FixedVectorTrack = 1;
  public static final byte DynamicVectorTrack = 2;
  public static final byte Framed16VectorTrack = 3;
  public static final byte Framed8VectorTrack = 4;

  public static final String[] names = { "NONE", "FixedVectorTrack", "DynamicVectorTrack", "Framed16VectorTrack", "Framed8VectorTrack", };

  public static String name(int e) { return names[e]; }
}

